services:
  unittests:
    build:
      context: .
      dockerfile: ./tests/unit/Dockerfile
    container_name: project_one_unittests
    environment:
      PYTHONPATH: /opt/commonpackages/src:/app/gateway/app:/app/website/app
    volumes:
      - ./commonpackages:/opt/commonpackages
      - ./gateway:/app/gateway
      - ./website:/app/website
      - ./tests:/app/tests
    command: pytest tests/unit -v --cov --cov-report=term-missing
    profiles:
      - test
         
  sensorsimulator:
    build:
      context: .
      dockerfile: ./tests/integration/Dockerfile
    container_name: project_one_sensorsimulator
    environment:
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-project_one_db}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-admin}
      IOTGATEWAY: http://project_one_gateway:8000/api/data
    volumes:
      - ./tests/integration:/app
    restart: unless-stopped

volumes:
  postgres_data:
  rabbitmq_data:
